[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ciri/iese-dsfb/blob/main/notebooks/010-Numpy.ipynb)

# NumPy: Numerical Python

## Why learn Numpy?

In today's data-driven world, everything can be quantified and represented as numbers—from user behavior on websites to patterns in medical data. Understanding these numerical representations is essential for machine learning, data analysis, and scientific computing. NumPy serves as the foundational package for numerical operations in Python, making it easier for you to delve into these domains.


## Numpy Arrays

This tutorial introduces you to NumPy's data containers, offering a quick look at how to manage data sets in Python. In the realm of mathematics, **vectors** and **matrices** are fundamental units represented as sequences and grids of numbers, respectively. They are integral to linear algebra, a crucial area in computational tasks underlying modern Machine Learning and Artificial Intelligence. In NumPy, these structures are simplified as one-dimensional (1D) and two-dimensional (2D) arrays, and the library even supports higher-dimensional arrays with ease.

To get started, import NumPy like this:

In [1]:
import numpy as np

A 1D arrays can be created from a list with the NumPy function array. If the items of the list have different
type, they are converted to a common type when creating the array. A simple example follows.

In [2]:
mylist = [2, 7, 14, 5, 9]
mylist

[2, 7, 14, 5, 9]

In [3]:
type(mylist)

list

In [4]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

This looks the same, but it's a very different beast! The constraint that everything has the same type is a useful one as it allows us to operate on the array more naturally. Try these for comparison:

In [5]:
print(arr1 + 1)
print(mylist + [1])
print(arr1 * 2)
print(mylist * 2)

[2 3 4 5]
[2, 7, 14, 5, 9, 1]
[2 4 6 8]
[2, 7, 14, 5, 9, 2, 7, 14, 5, 9]


In case of mixed types (never do this!) you will get unexpected results:

In [6]:
arr_mixed = np.array([1,'a',3,4])
arr_mixed

array(['1', 'a', '3', '4'], dtype='<U21')

There are two types involves with arrays. The type of the array is `array`, its elements also have a type which can be checked using `myarray.dtype`:

In [7]:
type(arr_mixed)

numpy.ndarray

In [8]:
arr_mixed.dtype

dtype('<U21')

A 2D array can be directly created from a list of lists of equal length. The terms are entered row-by-row:

In [9]:
my_list_of_lists = [
    [0, 7, 2, 3], 
    [3, 9, -5, 1]
]
my_list_of_lists

[[0, 7, 2, 3], [3, 9, -5, 1]]

In [10]:
arr2 = np.array(my_list_of_lists)
arr2

array([[ 0,  7,  2,  3],
       [ 3,  9, -5,  1]])

Although we visualize a vector as a column (or as a row) and a matrix as a rectangular arrangement, with rows and columns, it is not so in the computer. The 1d array is just a sequence of elements of the same type, neither horizontal nor vertical. It has one **axis**, which is the 0-axis.

In a similar way, a 2d array is a sequence of 1d arrays of the same length and type. It has two axes. When we visualize it as rows and columns, `axis=0` means *across rows*, while `axis=1` means *across columns*.

The number of terms stored along an axis is the **dimension** of that axis. The dimensions are collected in the attribute `shape`:

In [11]:
arr1.shape

(4,)

In [12]:
arr2.shape

(2, 4)

In [13]:
arr3 = np.random.randn(2,3,4)
arr3.shape

(2, 3, 4)

This is a tuple, meaning that you can extract one of the elements, but you cannot reassign it.

In [14]:
print(arr2.shape[0])

2


In [15]:
arr2.shape[0] = 123

TypeError: 'tuple' object does not support item assignment

**You try it:**

1. Create a prediction function `price` that predicts the price of an appartment based on its surface:

    Price = 100,000 + 5,000 x (surf in m2)

2. Calculate the price of a house of 130 m2.
3. Calculate the price over a range of surfaces 50,60,..,130

In [16]:
...

Ellipsis

## NumPy functions

NumPy incorporates vectorized forms of the **mathematical functions** of the package `math`. A **vectorized function** is one that, when applied to an array, returns an array with same shape, whose terms are the values of the function on the corresponding terms of the original array. For instance, the NumPy function `np.max` takes the maximum along an axis of a numeric array:

In [17]:
# Heights in cm [Female, Male]
heights = np.array([[160, 175],  
                    [155, 180],  
                    [165, 170],  
                    [162, 178],  
                    [158, 172]])
np.max(heights, axis=0)

array([165, 180])

In [18]:
heights.shape

(5, 2)

You can also tell `numpy` to do this calculation along the rows or columns using the `axis` parameter. Let's try calculating the mean for Females v.s. Males using the `np.mean()` function.

In [19]:
np.mean(heights ,axis=0)

array([160., 175.])

NumPy also provides common mathematical and statistical functions, such as `median, max, sum, sqrt, std, quantile` etc.


Functions that are defined in terms of vectorized functions are automatically vectorized. Let's try this with an exercise:

**You try it:**

Given the heights and weights of Females and Males, calculate the BMI of the whole population. Remember that the formula for BMI is:

$$
    \text{BMI} = \frac{\text{weight}}{\text{height (in meter)}^2}
$$

In [20]:
# Weights in kg [Female, Male]
heights =    np.array([[160, 175],
                       [155, 180],
                       [165, 170],
                       [162, 178],
                       [158, 172]])

weights = np.array([[55, 70],
                    [52, 77],
                    [58, 68],
                    [54, 75],
                    [53, 72]])

def bmi(h, w):
    # complete me ...
    return 0

## Subsetting arrays

**Slicing** a 1D array is done the same as for a list:

In [21]:
arr1 = np.array([5,4,2,41])
arr1[0]

np.int64(5)

In [22]:
arr1[:3]

array([5, 4, 2])

The same applies to two-dimensional arrays, but we need two indexes within the square brackets. The first index selects the rows (`axis=0`), and the second index the columns (`axis=1`):

In [23]:
heights[[1,2], :]

array([[155, 180],
       [165, 170]])

**Step intervals** can be used if we need to select only every n-th element of the array:

In [24]:
arr1, arr1[::2]

(array([ 5,  4,  2, 41]), array([5, 2]))

One special case of this which is used quite often is to use steps of -1, which is equivalent to reversing the array.

In [25]:
arr1, arr1[::-1]

(array([ 5,  4,  2, 41]), array([41,  2,  4,  5]))

In [26]:
arr1

array([ 5,  4,  2, 41])

In [27]:
arr1[::2]

array([5, 2])

Here's an overview of common slicing operations from McKinney (2017):

<center>
    <img src='https://raw.githubusercontent.com/ciri/iese-dsfb/main/images/nparray-indexing.png' width='60%'>
</center>

**Filtering** Subsets of an array can also be extracted by means of expressions which acts as filters. Any expression involving an array is evaluated in Python as a Boolean array (called a **Boolean mask**):

In [28]:
f_tall           = heights >= 160 
f_tall

array([[ True,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [False,  True]])

We can use this as an index, and it will remove anyone in the dataset who is too tall:

In [29]:
heights[f_tall]

array([160, 175, 180, 165, 170, 162, 178, 172])

These can be combined into complex expressions as suited for the application:

In [30]:
filter_tall   = heights > 160
filter_short  = heights < 180
heights[filter_tall & filter_short ]

array([175, 165, 170, 162, 178, 172])

Since both heights and weights are of the same size, we can filter either on the other:

In [31]:
weights[filter_tall]

array([70, 77, 58, 68, 54, 75, 72])

### Extra exercises for home

**You try it**

What is the average BMI of people taller than 170cm?

**You try it**

Try to change the BMI function so that instead of given you your BMI, it returns a classification (string). The BMI classifications are:

* Below 18.5	Underweight
* 18.5 – 24.9	Healthy Weight
* 25.0 – 29.9	Overweight
* 30.0 and Above	Obesity

**You try it**

Let's perform RFM (Recency, Frequency, Monetary) analysis - a key technique in customer segmentation and marketing analytics.

RFM analysis is a behavior-based technique used to segment customers by examining their transaction history. It evaluates customers based on three dimensions:

- **Recency (R)**: How recently a customer has made a purchase.
- **Frequency (F)**: How often a customer makes a purchase.
- **Monetary Value (M)**: How much money a customer spends on purchases.

The idea of this battle-tested technique is that it allows us to (a) categorize customers into distinct groups for targeted marketing (b) find out recent / frequent buyers which are more likely to respond to new offers (c) focus efforts on segments that are more likely to generate higher returns.

Let's start with generating the dataset (you don't need to worry about this code for now).


In [32]:
import numpy as np

def generate_rfm_aggregate_data(num_customers=100, max_days_since_last_purchase=365, max_frequency=25, max_monetary=10000):
    """
    Generate synthetic aggregate RFM data for customers.

    Parameters:
    - num_customers: int, number of unique customers.
    - max_days_since_last_purchase: int, maximum number of days since the last purchase.
    - max_frequency: int, maximum number of transactions made by a customer.
    - max_monetary: int, maximum total amount spent by a customer.

    Returns:
    - data: np.ndarray, 2D array with columns: CustomerID, Recency, Frequency, Monetary.
    """
    np.random.seed(42)  # For reproducibility

    recency   = np.random.randint(1, max_days_since_last_purchase + 1, num_customers)
    frequency = np.random.randint(1, max_frequency + 1, num_customers)
    monetary  = np.round(np.random.uniform(10.0, max_monetary, num_customers), 2)

    data = np.column_stack((recency, frequency, monetary))

    return data

rfm_data = generate_rfm_aggregate_data(num_customers=1000)

**You try it**

Create a function `rfm_score` that computes a simple RFM score:
    
    Score = (max_recency - recency) + frequency + (monetary / 1000)

Higher is better.

In [ ]:
# RFM 
# **You try it:**

# 1. Create a function `rfm_score` that computes a simple RFM score:
#    Score = (max_recency - recency) + frequency + (monetary / 1000)
#    where higher scores mean better customers.

def rfm_score(data):
    # complete me
    return 0

# 2. Compute RFM scores for all customers.
scores = rfm_score(rfm_data)

# 3. Find top 5 customers with the highest scores.
top5_idx = np.argsort(scores)[-5:][::-1]
print("Top 5 customers (indices):", top5_idx)
print("Top 5 scores:", scores[top5_idx])

Top 5 customers (indices): [0]


TypeError: 'int' object is not subscriptable

## SOLUTIONS

In [43]:
def calc_price(surf):
    return 100000 + 50000 * surf

## Price of a house of 130 m2
calc_price(130)

## Price of a range of surfaces
surfaces = np.array(list(range(50, 131)))
prices   = calc_price(surfaces)

In [80]:
# Weights in kg [Female, Male]
heights =    np.array([[160, 175],
                       [155, 180],
                       [165, 170],
                       [162, 178],
                       [158, 172]])

weights = np.array([[55, 70],
                    [52, 77],
                    [58, 68],
                    [54, 75],
                    [53, 72]])

## long version
def bmi(h, w):
    return w / (h / 100.)**2

# short version
bmi = lambda h, w: w / (h / 100.)**2

# apply to all customers
all_bmis = bmi(heights, weights)

# average
np.mean(all_bmis, axis=0)

array([21.2478296 , 23.63214401])

In [81]:
# Average height of people taller than 170cm
all_bmis = bmi(heights, weights)

filter_tall = heights > 170

np.mean(all_bmis[filter_tall], axis=0)

np.float64(23.65782707606685)

In [87]:
# Simple version
def bmi_classification(h,w):
    bmi = w / (h / 100.)**2

    if bmi < 18.5:
        return "Underweight"
    elif bmi >= 18.5 and bmi <= 24.9:
        return "Healthy Weight"
    elif bmi >= 25.0 and bmi <= 29.9:
        return "Overweight"

bmi_classification(180, 70)

'Healthy Weight'

In [90]:
## RFM
rfm_data = generate_rfm_aggregate_data(num_customers=1000)

def rfm_score(data):
    score = (np.max(data[:, 0]) - data[:, 0]) + data[:, 1] + (data[:, 2] / 1000)
    return np.round(score)

# 2. Compute RFM scores for all customers.
scores = rfm_score(rfm_data)

# 3. Find top 5 customers with the highest scores.
top5_idx = np.argsort(scores)[-5:][::-1]
print("Top 5 customers (indices):", top5_idx)
print("Top 5 scores:", scores[top5_idx])

Top 5 customers (indices): [895 446 613 648 842]
Top 5 scores: [394. 392. 391. 389. 389.]
